---
sudo: required
language: python
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule ansible
script:
  - ansible-lint .
notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/?branch=master
    on_failure: never
