---
# tasks file for ansible-haya

- name: "Install required packages"
  apt:
    name: "{{ packages }}"
    cache_valid_time: 3600
  vars:
    packages:
      - ntp
      - python3-pip

- name: Login to docker registry
  include_tasks: "init.yml"

- name: Show debug variables
  include_tasks: "debug/show-state.yml"
  tags:
    - never
    - debug

- name: Set host parameters for debugging services
  include_tasks: "docker/debugging.yml"

- name: Login to docker registry
  include_tasks: "docker/registry.yml"

- name: "Setup docker network"
  include_tasks: "docker/network.yml"

- name: "Install blockchain components"
  include_tasks: "blockchain/{{ bc_name }}/main.yml"
