---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements.yml
    #  name: shell
    #  command: mkdir -p /tmp/molecule/plugins; git clone https://github.com/dw/mitogen.git /tmp/molecule/plugins/mitogen
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: boot
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: producer
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: monitoring
    image: paulfantom/ubuntu-molecule:18.04
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: playbook.yml
    destroy: destroy.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      interpreter_python: auto
      deprecation_warnings: False
      #      strategy_plugins: /Users/alevkin/w/mixbytes/git/mixbytes/tank.ansible-haya/env/lib/python3.7/site-packages/ansible_mitogen/plugins/strategy
      #      strategy: mitogen_linear
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlPersist=6000s -o ControlMaster=auto -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
scenario:
  name: full
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
