---
- name: "Make directory structure"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_data }}"
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"

- name: set config.ini
  vars:
    producer_name: "{{ bc_haya_boot.name }}"
    producer_pub_key: "{{ bc_haya_boot.pub_key }}"
    producer_pvt_key: "{{ bc_haya_boot.pvt_key }}"
  template:
    src: "{{ bc_path_config_template }}"
    dest: "{{ bc_path_config }}/config.ini"

- name: set genesis.json
  template:
    src: "{{ bc_path_genesis_template }}"
    dest: "{{ bc_path_config }}/genesis.json"

- name: set logger.json
  tags:
    - update
  template:
    src: "{{ bc_path_logger_template }}"
    dest: "{{ bc_path_config }}/logger.json"

- name: Start boot-node container
  register: _start_boot_node
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: "{{ bc_haya_image }}"
    command: |
      /opt/haya/bin/haya-node
      --config-dir={{ bc_path_config }}
      --genesis-json={{ bc_path_config }}/genesis.json
      --logconf={{ bc_path_config }}/logger.json
    hostname: "{{ bc_name }}-{{ bc_component_name }}"
    network_mode: host
    volumes:
      - "{{ bc_path_state }}:/root/.local"
      - "{{ bc_path_config }}:{{ bc_path_config }}"
      - "{{ bc_path_contracts }}:{{ bc_path_contracts }}"
      - "/tmp/cores:/tmp/cores"
    capabilities:
      - IPC_LOCK
    stop_timeout: 600
    pull: true
    log_driver: "{{ bc_docker_log_driver | default(omit) }}"
    log_options:
      max-size: "{{ '1g' if bc_docker_log_driver == 'json-file' else omit }}"
      fluentd-async-connect: "{{ 'true' if bc_docker_log_driver == 'fluentd' else omit }}"
      fluentd-address: "{{ 'localhost:24224' if bc_docker_log_driver == 'fluentd' else omit  }}"

- name: "Check container health"
  uri:
    url: "http://localhost:{{ bc_haya_node_http_port }}/v1/chain/get_info"
    method: GET
    status_code: 200
  register: boot_status
  retries: 10
  delay: 5
  until: boot_status is success
