---
- name: "OS settings"
  hosts: all
  become: true
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: true
    - name: "Configuring ulimit"
      block:
        - pam_limits:
            domain: root
            limit_type: soft
            limit_item: nofile
            value: 65536
        - pam_limits:
            domain: root
            limit_type: hard
            limit_item: nofile
            value: 65536
        - pam_limits:
            domain: '*'
            limit_type: soft
            limit_item: nofile
            value: 65536
        - pam_limits:
            domain: '*'
            limit_type: hard
            limit_item: nofile
            value: 65536

- name: Prepare 2
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: geerlingguy.docker
