---
- name: "Set facts"
  set_fact:
    bc_haya_system_accounts:
      - eosio.bpay
      - eosio.msig
      - eosio.names
      - eosio.ram
      - eosio.ramfee
      - eosio.saving
      - eosio.stake
      - eosio.token
      - eosio.vpay
      - eosio.rex
    bc_haya_system_contracts:
      - { name: eosio.token, wasm_path: eosio.token/eosio.token.wasm, abi_path: eosio.token/eosio.token.abi }
      - { name: eosio.msig, wasm_path: eosio.msig/eosio.msig.wasm, abi_path: eosio.msig/eosio.msig.abi }
      - { name: eosio, wasm_path: eosio.system/eosio.system.wasm, abi_path: eosio.system/eosio.system.abi }

- include_tasks: "boot-common.yml"

- name: import bootstrap producer key into wallet
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    wallet import --private-key {{ bc_haya_boot.pvt_key }} && \
    touch {{ bc_path_state }}/importbootkey
  args:
    creates: "{{ bc_path_state }}/importbootkey"
  register: import_producer_key
  ignore_errors: true

- debug:
    msg: "{{ import_producer_key.stderr_lines }}"
  tags:
    - never
    - debug
- debug: var=import_producer_key.stdout_lines
  tags:
    - never
    - debug

- name: create system accounts
  loop: "{{ bc_haya_system_accounts }}"
  register: create_system_accounts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    create account -x 45 eosio {{ item }} {{ bc_haya_boot.pub_key }} {{ bc_haya_boot.pub_key }} && \
    touch {{ bc_path_state }}/createsysacc-{{ item }}
  args:
    creates: "{{ bc_path_state }}/createsysacc-{{ item }}"
  changed_when: "'executed transaction' in create_system_accounts.stdout"

- name: Show stderr from create system accounts task
  debug:
    msg: "DEBUG: \n stderr:{{ item.stderr }}\n stdout:{{ item.stdout }}"
  loop: "{{ create_system_accounts.results }}"
  tags:
    - never
    - debug

# FIXME:
#   "message": "protocol feature with digest '0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd' has already been activated",
# (when provisioning)
- name: Activate the PREACTIVATE_FEATURE protocol
  shell: |
    curl --request POST \
      --url http://localhost:{{ bc_haya_node_http_port }}/v1/producer/schedule_protocol_feature_activations \
      -d '{"protocol_features_to_activate": ["0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd"]}' && \
    touch {{ bc_path_state }}/activated_PREACTIVATE_FEATURE
  args:
    creates: "{{ bc_path_state }}/activated_PREACTIVATE_FEATURE"
#~  uri:
#~    url: http://localhost:{{ bc_haya_node_http_port }}/v1/producer/schedule_protocol_feature_activations
#~    method: POST
#~    body: '{"protocol_features_to_activate": ["0ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd"]}'
#~    status_code: 201

- name: set abi system contracts
  loop: "{{ bc_haya_system_contracts }}"
  register: set_abi_system_contracts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    set abi {{ item.name }} /host/{{ bc_path_contracts }}/{{ item.abi_path }} && \
    touch {{ bc_path_state }}/setabisyscontracts-{{ item.name }}
  args:
    chdir: "{{ bc_path_contracts }}"
    creates: "{{ bc_path_state }}/setabisyscontracts-{{ item.name }}"

- name: Show stderr from set abi system contracts task
  debug:
    msg: "DEBUG: \n stderr:{{ item.stderr }}\n stdout:{{ item.stdout }}"
  loop: "{{ set_abi_system_contracts.results }}"
  tags:
    - never
    - debug

- name: set code system contracts
  loop: "{{ bc_haya_system_contracts }}"
  register: set_code_system_contracts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    set code {{ item.name }} /host/{{ bc_path_contracts }}/{{ item.wasm_path }} && \
    touch {{ bc_path_state }}/setcodesyscontracts-{{ item.name }}
  args:
    chdir: "{{ bc_path_contracts }}"
    creates: "{{ bc_path_state }}/setcodesyscontracts-{{ item.name }}"

- name: Show stderr from set code system contracts task
  debug:
    msg: "DEBUG: \n stderr:{{ item.stderr }}\n stdout:{{ item.stdout }}"
  loop: "{{ set_code_system_contracts.results }}"
  tags:
    - never
    - debug

- include_tasks: "boot-checks.yml"

- name: create token
  register: create_token
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio.token create '["eosio", "{{ bc_haya_max_tokens_amount }} \
    {{ bc_haya_token_symbol }}"]' -p eosio.token && \
    touch {{ bc_path_state }}/createtoken
  args:
    creates: "{{ bc_path_state }}/createtoken"

- name: Show stderr from create token task
  debug:
    msg: "DEBUG: \n stderr:{{ create_token.stderr }}\n stdout:{{ create_token.stdout }}"
  tags:
    - never
    - debug

- name: allocate tokens
  register: allocate_tokens
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio.token issue '["eosio", "{{ bc_haya_tokens_amount }} \
    {{ bc_haya_token_symbol }}", "memo"]' -p eosio && \
    touch {{ bc_path_state }}/allocatetokens
  args:
    creates: "{{ bc_path_state }}/allocatetokens"

- name: Show stderr from allocate tokens task
  debug:
    msg: "DEBUG: \n stderr:{{ allocate_tokens.stderr }}\n stdout:{{ allocate_tokens.stdout }}"
  tags:
    - never
    - debug

- name: Init system contracts
  register: init_system_contracts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio init '[0,"4,{{ bc_haya_token_symbol }}"]' -p eosio && \
    touch {{ bc_path_state }}/initsyscontracts-eosio
  args:
    creates: "{{ bc_path_state }}/initsyscontracts-eosio"
    chdir: "{{ bc_path_contracts }}"

- name: Show stderr from init system contracts task
  debug:
    msg: "DEBUG: \n stderr:{{ item.stderr }}\n stdout:{{ item.stdout }}"
  loop: "{{ init_system_contracts.results }}"
  tags:
    - never
    - debug

- name: Make eosio.msig a privileged account
  register: make_msig_privileged_account
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio setpriv '["eosio.msig", 1]' -p eosio@active && \
    touch {{ bc_path_state }}/makemsigprivilegedaccaont-eosio

- name: Show stderr from make eosio.msig a privileged account task
  debug:
    msg: "DEBUG: \n stderr:{{ item.stderr }}\n stdout:{{ item.stdout }}"
  loop: "{{ make_msig_privileged_account.results }}"
  tags:
    - never
    - debug
