---
- name: "Set facts"
  set_fact:
    bc_haya_system_accounts:
      - eosio.bpay
      - eosio.msig
      - eosio.names
      - eosio.ram
      - eosio.ramfee
      - eosio.saving
      - eosio.stake
      - eosio.token
      - eosio.vpay
      - eosio.rex
    bc_haya_system_contracts:
      - { name: eosio.token, wasm_path: eosio.token/eosio.token.wasm, abi_path: eosio.token/eosio.token.abi }
      - { name: eosio.msig, wasm_path: eosio.msig/eosio.msig.wasm, abi_path: eosio.msig/eosio.msig.abi }
      - { name: eosio, wasm_path: eosio.system/eosio.system.wasm, abi_path: eosio.system/eosio.system.abi }

- include_tasks: "boot-common.yml"

- name: import bootstrap producer key into wallet
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    wallet import --private-key {{ bc_haya_boot.pvt_key }} && \
    touch {{ bc_path_state }}/importbootkey
  args:
    creates: "{{ bc_path_state }}/importbootkey"
  register: import_producer_key
  ignore_errors: true

- name: create system accounts
  loop: "{{ bc_haya_system_accounts }}"
  register: create_system_accounts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    create account -x 45 eosio {{ item }} {{ bc_haya_boot.pub_key }} {{ bc_haya_boot.pub_key }} && \
    touch {{ bc_path_state }}/createsysacc-{{ item }}
  args:
    creates: "{{ bc_path_state }}/createsysacc-{{ item }}"
  changed_when: "'executed transaction' in create_system_accounts.stdout"

- name: set abi system contracts
  loop: "{{ bc_haya_system_contracts }}"
  register: set_abi_system_contracts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    set abi {{ item.name }} /host/{{ bc_path_contracts }}/{{ item.abi_path }} && \
    touch {{ bc_path_state }}/setabisyscontracts-{{ item.name }}
  args:
    chdir: "{{ bc_path_contracts }}"
    creates: "{{ bc_path_state }}/setabisyscontracts-{{ item.name }}"

- name: set code system contracts
  loop: "{{ bc_haya_system_contracts }}"
  register: set_code_system_contracts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    set code {{ item.name }} /host/{{ bc_path_contracts }}/{{ item.wasm_path }} && \
    touch {{ bc_path_state }}/setcodesyscontracts-{{ item.name }}
  args:
    chdir: "{{ bc_path_contracts }}"
    creates: "{{ bc_path_state }}/setcodesyscontracts-{{ item.name }}"

- include_tasks: "boot-checks.yml"

- name: create token
  register: create_token
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio.token create '["eosio", "{{ bc_haya_max_tokens_amount }} \
    BET"]' -p eosio.token && \
    touch {{ bc_path_state }}/createtoken
  args:
    creates: "{{ bc_path_state }}/createtoken"

- name: allocate tokens
  register: allocate_tokens
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio.token issue '["eosio", "{{ bc_haya_tokens_amount }} \
    BET", "memo"]' -p eosio && \
    touch {{ bc_path_state }}/allocatetokens
  args:
    creates: "{{ bc_path_state }}/allocatetokens"

- name: Init system contracts
  register: init_system_contracts
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    push action eosio init '[0,"4,BET"]' -p eosio && \
    touch {{ bc_path_state }}/initsyscontracts-eosio
  args:
    creates: "{{ bc_path_state }}/initsyscontracts-eosio"
    chdir: "{{ bc_path_contracts }}"

- name: create producers account
  loop: "{{ bc_haya_producer_accounts_pub }}"
  register: create_producers_account
  shell: |
    {{ bc_haya_cli }} \
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }} \
    --url=http://localhost:{{ bc_haya_node_http_port }} \
    system newaccount -x 45 eosio --transfer {{ item.name }} \
    {{ item.pub_key }} --stake-net "10.0000 BET" \
    --stake-cpu "10.0000 BET" --stake-vote "0.0000 BET" --buy-ram-kbytes 8192 && \
    touch {{ bc_path_state }}/createprodacc-{{ item.name }}
  args:
    creates: "{{ bc_path_state }}/createprodacc-{{ item.name }}"
  retries: 5
  delay: 3
  until: create_producers_account is success
  loop_control:
    index_var: index
