---
- name: "Make directory structure"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_data }}"
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"

- name: "Start {{ bc_name }} container"
  tags:
    - update
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: "{{ bc_haya_image }}"
    command: "/opt/{{ bc_name }}/bin/{{ bc_name }}-wallet
    --unlock-timeout=99999999 --wallet-dir {{ bc_path_data }}
    --http-server-address=0.0.0.0:{{ bc_haya_wallet.port }}
    --http-alias=haya-wallet:{{ bc_haya_wallet.port }}
    --http-alias=localhost:{{ bc_haya_wallet.port }}"
    hostname: "{{ bc_name }}-wallet"
    ports:
      - "{{ bc_haya_wallet.port }}:{{ bc_haya_wallet.port }}"
    expose:
      - "{{ bc_haya_wallet.port }}"
    volumes:
      - "{{ bc_path_data }}:{{ bc_path_data }}"
    capabilities:
      - IPC_LOCK
    stop_timeout: 600
    networks:
      - name: "{{ bc_name }}-net"
    log_driver: "{{ bc_docker_log_driver | default(omit) }}"
    log_options:
      max-size: "{{ '1g' if bc_docker_log_driver == 'json-file' else omit }}"
      fluentd-async-connect: "{{ 'true' if bc_docker_log_driver == 'fluentd' else omit }}"
      fluentd-address: "{{ 'localhost:24224' if bc_docker_log_driver == 'fluentd' else omit  }}"

- name: Create default wallet
  shell:
    cmd: "{{ bc_haya_cli }}
    --wallet-url=http://localhost:{{ bc_haya_wallet.port }}
    wallet create -f {{ bc_path_general }}/{{ bc_name }}/{{ bc_name }}-cli/wallet.password"
  register: create_wallet
  args:
    creates: "{{ bc_path_general }}/{{ bc_name }}/{{ bc_name }}-cli/wallet.password"

- debug:
    msg: "{{ create_wallet.stderr_lines }}"
  tags:
    - never
    - debug

- debug:
    msg: "{{ create_wallet.stdout_lines }}"
  tags:
    - never
    - debug
