---
- name: Send the load profile to the nodes
  hosts: "*producer*"
  become: true
  tasks:
    - name: "Send the load profile {{ load_profile_local_file }} to the nodes"
      tags: [send_load_profile]
      copy:
        src: "{{ load_profile_local_file }}"
        dest: "/opt/bench/profile.js"
